name: Increment Version
 
on:
  pull_request:
    branches:
      - develop
    types: [closed]
 
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
 
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
 
      - name: Increment version in pom.xml
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
          mvn versions:set -DnewVersion=$new_version
          mvn versions:commit
 
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "Increment version to $new_version"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

